image: drone/phpgrade:latest
script:
  - git clone --branch=ghpages git@git.drutch.nl:build2be/php-grade.git /home/ubuntu/pkg
  - php-grade run -f angular -t phpcs -t phpmd -o /home/ubuntu/pkg /home/ubuntu/src
notify:
  email:
    recipients:
      - martijn@brixit.nl
deploy:
  bash:
    script:
      - cd /home/ubuntu/pkg && git add --all
      - cd /home/ubuntu/pkg && git commit -am "Grade result updated"
      - cd /home/ubuntu/pkg && git push