<?php

namespace PhpGrade\Commands;

use PhpGrade\Formatters\AngularFormatter;
use PhpGrade\Formatters\ConsoleFormatter;
use PhpGrade\Formatters\YamlFormatter;
use PhpGrade\MessageList;
use PhpGrade\Parsers\ParserInterface;
use PhpGrade\Parsers\PhpCpdParser;
use PhpGrade\Parsers\PhpCsParser;
use PhpGrade\Parsers\PhpDcdParser;
use PhpGrade\Parsers\PhpMdParser;
use PhpGrade\Parsers\PhpSecurityParser;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Finder\Finder;


class RunCommand extends BaseCommand
{

    protected function configure()
    {
        $this
          ->setName('run')
          ->setDescription('Run all available grading types.')
          ->addOption(
            'tests',
            't',
            InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
            'Test programs to run (all by default) options: phpcs, phpmd, phpdcd, phpcpd.'
          )
          ->addOption(
            'format',
            'f',
            InputOption::VALUE_REQUIRED,
            'Set output formatter (console by default) options: console, yaml, angular.',
            'console'
          )
          ->addOption(
            'output-dir',
            'o',
            InputOption::VALUE_REQUIRED,
            'Output directory for angular formatter.'
          )
          ->addOption(
            'serve',
            's',
            InputOption::VALUE_NONE,
            'Run PHP built-in webserver on the output directory for angular.'
          )
          ->addArgument(
            'location',
            InputArgument::REQUIRED,
            'Location to grade. This can be a file or directory.'
          )
        ;
    }

    /**
     * Run all available grading (sub) commands
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $location = $input->getArgument('location');
        if (!file_exists($location)) {
            throw new \Exception("Location $location does not exists.");
        }

        $tools = $input->getOption('tests');
        if (empty($tools) || $tools === null) {
            $tools = array('all');
        }

        $parsers = array();
        if (in_array('phpcs', $tools) || in_array('all', $tools)) {
            $parsers[] = new PhpCsParser();
        }
        if (in_array('phpmd', $tools) || in_array('all', $tools)) {
            $parsers[] = new PhpMdParser();
        }
        if (in_array('phpcpd', $tools) || in_array('all', $tools)) {
            $parsers[] = new PhpCpdParser();
        }
        if (in_array('phpdcd', $tools) || in_array('all', $tools)) {
            $parsers[] = new PhpDcdParser();
        }
        if (in_array('security', $tools) || in_array('all', $tools)) {
            $parsers[] = new PhpSecurityParser();
        }

        $finder = new Finder();

        // Skip vendor directories
        $finder->files()->in($location)->notPath("vendor");

        // List of messages generated by each grader.
        $messages = new MessageList();

        foreach ($parsers as $parser) {
            /**
             * @var Finder $finderInstance
             */
            $finderInstance = clone $finder;
            /**
             * @var ParserInterface $parser
             */
            $parser->run($finderInstance, $messages);
        }

        $outputDir = $input->getOption('output-dir');
        $serve = $input->getOption('serve');
        $format = $input->getOption('format');

        if ($format == 'console') {
            $formatter = new ConsoleFormatter();
        }
        else if ($format == 'yaml') {
            $formatter = new YamlFormatter();
        }

        if (!is_null($serve)) {
           $formatter = 'angular';
           if (is_null($output)) {
             $tempfile=tempnam(sys_get_temp_dir(),'phpgrade-');
             if (file_exists($tempfile)) {
               unlink($tempfile);
             }
             mkdir($tempfile);
             $output = $tempfile;
           }
        }

        if ($input->getOption('verbose')) {
            echo "Serve : $serve" . PHP_EOL;
            echo "Output dir: $output" . PHP_EOL;
            echo "Format: $formatter" . PHP_EOL;
        }

        if ($formatter == 'angular') {
            $formatter = new AngularFormatter();
            $formatter->format($messages->getMessages(), $output, $serve);
        }else{
            $formatter->format($messages->getMessages());
        }

    }
}
